language: cpp

os:
  - linux

sudo: required
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - build-essential
      - cmake
      - cmake-data
      - git
      - libgtk2.0-dev
      - pkg-config
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - python-dev
      - python-numpy
      - libtbb2
      - libtbb-dev
      - libjpeg-dev
      - libpng-dev
      - libjasper-dev
      - libdc1394-22-dev
      - unzip

#env: GCC_VERSION=5 CPP=11 COMPILER=g++-5 CXX=g++-5 CC=gcc-5

install:
  - sudo apt-get install -y libtiff5 libtiff5-dev
#  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
#  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
  - git clone https://github.com/Itseez/opencv.git
  - cd opencv
  - mkdir build
  - cd build
  - cmake ..
  - make -j8
  - sudo make -j8 install
  - export OPENCV_DIR=/usr/local/lib
  - cd ../../build
  - wget https://github.com/livecv/livecv-deploy-kit/archive/master.zip
  - unzip master.zip
  - mv livecv-deploy-kit-master/* .
  - wget http://download.qt.io/official_releases/qt/5.7/5.7.0/qt-opensource-linux-x64-5.7.0.run
  - sudo chmod 777 qt-opensource-linux-x64-5.7.0.run
  - ./qt-opensource-linux-x64-5.7.0.run --script resources/install-qt.qs --verbose --silent -platform minimal
  - export QTDIR=/opt/qt/5.7/gcc_64


script:
  - ls
  - python3 livecv_build.py .. gcc_64
  - ls
  - find .
  - python3 livecv_deploy.py .. gcc_64
